spring.profiles.active=dev
server.port=9010
server.context-path=/tts
server.servlet.context-path=/tts


#开启日志(简单开启日志的方式，如果有logback-spring.xml等配置，则可以注释)
#logging.level.root=info
#logging.level.com.yh.bigdata.tts.common.dao=debug
#logging.level.org.springframework.web=INFO
#logging.level.org.apache.http=info
#logging.file=logs/tts/tts-api.log
log.path=logs/


#mybatis相关的配置
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.yh.bigdata.tts.common.model

custom.datasource.names=default
#custom.datasource.default.driver-class-name=com.mysql.jdbc.Driver
custom.datasource.default.driver-class-name=com.mysql.cj.jdbc.Driver
#custom.datasource.default.url=jdbc:mysql://10.251.136.13:3306/tts
#custom.datasource.default.username=dws_dev
#custom.datasource.default.password=*gdW9AJItBkP
custom.datasource.default.url=jdbc:mysql://localhost:3306/tts?userUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
custom.datasource.default.username=root
custom.datasource.default.password=root1234

realtime.spider.on=false
#realtime.spider.on=false
#day.all.spider.cron=0 10 15 * * 1-5
day.all.spider.cron=0 10 15 * * 7
#realtime.spider.cron=0/5 * 9-11,13-14 * * 1-5
realtime.spider.cron=0/10 * 9-11,13-14 * * 1-5
#realtime.spider.cron=0 0 0 1 1 1
realtime.check.cron=0/30 * 9-11,13-14 * * 1-5
min30.spider.cron=0 0/2 9-11,13-14 * * 1-5
#min30.spider.cron=0 0 0 * * 1-5



#last.trade.day=2019-04-24
#last.trade.week=2019-04-19
spider.day.interval=200
spider.day.startpage=1
spider.week.startpage=1
spider.month.startpage=1
spider.year.startpage=1
spider.notice.startpage=1
spider.report.startpage=1
spider.min15.startpage=1
spider.min30.startpage=1
spider.min60.startpage=1



